version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:q159@db/insurance_db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q159
      POSTGRES_DB: insurance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
