version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - insurance_service
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:q159@db/insurance_db
      - KAFKA_IP=kafka
      - KAFKA_PORT=9092

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q159
      POSTGRES_DB: insurance_db
    networks:
      - insurance_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      timeout: 5s
      interval: 5s
    ports:
      - "2181:2181"
    networks:
      - insurance_service

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    healthcheck:
      test: [ "CMD-SHELL", "echo 'test-message' | kafka-console-producer.sh --broker-list 
      localhost:9092 --topic health-check-topic && kafka-console-consumer.sh --bootstrap-server 
      localhost:9092 --topic health-check-topic --from-beginning --max-messages 1 | grep 'test-message'" ]
      interval: 15s
      timeout: 10s
      retries: 3
    ports:
      - "9092:9092"
    networks:
      - insurance_service

networks:
  insurance_service:

volumes:
  postgres_data:
